import { useEffect, useState } from 'react'
import { api, post } from './api'
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from '../support'
type RemovalRequest={id:string;status:'requested'|'reviewing'|'completed'|'cancelled';created_at:string;updated_at:string}
type ReviewRequest=RemovalRequest&{user_id:string;username:string|null;review_note:string}
const labels={requested:'Requested',reviewing:'Under review',completed:'Completed',cancelled:'Cancelled'}
type MailCount={day:string;purpose:'verify'|'reset';accepted:number;failed:number;limited:number}
function errorText(error:unknown){return error instanceof Error?error.message:'The request could not be completed.'}
export function AccountRemovalRequest(){
 const [request,setRequest]=useState<RemovalRequest|null|undefined>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false)
 useEffect(()=>{let cancelled=false;void api<RemovalRequest|null>('/auth/account-removal').then(value=>{if(!cancelled)setRequest(value)}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[])
 const active=request&&(request.status==='requested'||request.status==='reviewing')
 async function send(form:HTMLFormElement){setBusy(true);setError('');try{setRequest(await post<RemovalRequest>('/auth/account-removal',{password:new FormData(form).get('password'),confirm:'REQUEST'}));form.reset();setConfirmed(false)}catch(error){setError(errorText(error))}finally{setBusy(false)}}
 async function withdraw(){setBusy(true);setError('');try{await api('/auth/account-removal',{method:'DELETE'});setRequest(await api<RemovalRequest|null>('/auth/account-removal'))}catch(error){setError(errorText(error))}finally{setBusy(false)}}
 return <section className="configuration-section"><h2>Account removal</h2><p>Send a private request to the administrator to remove your account and its data. Your account stays active while the request is reviewed. The administrator will confirm the handling of shared discussions before removal.</p><p className="service-note">For help with a request, contact <a href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. Never send passwords, recovery links or firmware.</p>{active?<><p className="success-note" role="status">{labels[request.status]} · requested {new Date(request.created_at.replace(' ','T')+'Z').toLocaleDateString()}</p><button className="button button-quiet" disabled={busy} onClick={()=>void withdraw()}>{busy?'Saving…':'Withdraw request'}</button></>:request===undefined&&!error?<p role="status">Loading account requests…</p>:<details><summary>Request account removal</summary>{request&&<p>Previous request: {labels[request.status]}.</p>}<form className="community-form" onSubmit={event=>{event.preventDefault();void send(event.currentTarget)}}><label>Current password<input name="password" type="password" autoComplete="current-password" required minLength={15} maxLength={128}/></label><label className="risk-accept"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} required/>I want the administrator to remove my account.</label><button className="button button-quiet" disabled={busy||!confirmed}>{busy?'Sending…':'Send removal request'}</button><p className="service-note">This requests removal; it does not delete data immediately. You can withdraw the request while it is pending.</p></form></details>}{error&&<p className="file-error" role="alert">{error}</p>}</section>
}
export function AccountRequestInbox(){
 const [items,setItems]=useState<ReviewRequest[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 useEffect(()=>{let cancelled=false;void api<ReviewRequest[]>('/admin/account-requests').then(items=>{if(!cancelled)setItems(items)}).catch(error=>{if(!cancelled)setError(errorText(error))}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[])
 async function review(id:string,form:HTMLFormElement){setBusy(id);setError('');try{await post('/admin/account-requests/'+id,Object.fromEntries(new FormData(form)),'PATCH');setItems(await api<ReviewRequest[]>('/admin/account-requests'))}catch(error){setError(errorText(error))}finally{setBusy('')}}
 return <section className="configuration-section"><h2>Private account requests</h2><p className="service-note">Submitting and reviewing a request never deletes account data. Obtain and record approval for the specific removal scope, follow the operator procedure, then verify removal before marking completion. The server rejects completion while account credentials or private reports remain.</p>{loading?<p role="status">Loading requests…</p>:items.length?items.map(item=><article className="inbox-issue" key={item.id}><div className="section-title"><h3>{item.username?'@'+item.username:'Removed account'}</h3><span className="pill">{labels[item.status]}</span></div><small>Request {item.id} · account {item.user_id} · {item.created_at}</small>{item.review_note&&<p>{item.review_note}</p>}{(item.status==='requested'||item.status==='reviewing')&&<form className="community-form" onSubmit={event=>{event.preventDefault();void review(item.id,event.currentTarget)}}><label>Review action<select name="status"><option value="reviewing">Under review</option><option value="cancelled">Cancel request</option><option value="completed">Confirm verified completion</option></select></label><label>Private review note<textarea name="note" required maxLength={1000} rows={2}/></label><button className="button button-quiet" disabled={!!busy}>{busy===item.id?'Saving…':'Save review'}</button></form>}</article>):!error&&<p className="service-note">No account-removal requests.</p>}{error&&<p className="file-error" role="alert">{error}</p>}</section>
}
export function AccountMailHealth(){
 const [rows,setRows]=useState<MailCount[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let cancelled=false;void api<MailCount[]>('/admin/account-mail').then(value=>{if(!cancelled)setRows(value)}).catch(error=>{if(!cancelled)setError(errorText(error))}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[])
 return <section className="configuration-section"><h2>Account email</h2><p className="service-note">Private daily counts of verification and recovery attempts. Accepted means the provider accepted the message; inbox delivery must be checked in Resend. These counts contain no addresses, links or provider responses.</p>{loading?<p role="status">Loading email counts…</p>:rows.length?rows.map(row=><p key={row.day+row.purpose}><strong>{row.day} · {row.purpose==='verify'?'Verification':'Recovery'}</strong> — {row.accepted} accepted · {row.failed} failed · {row.limited} limited</p>):!error&&<p>No email attempts recorded.</p>}{error&&<p role="alert" className="file-error">{error}</p>}</section>
}
