import { useEffect, useState } from 'react'
import { api, post } from './api'
import { useCommunity } from './context'
import { FORUM_CATEGORIES, type ForumCategory, type ForumPost, type ForumThread, type SharedConfiguration, type ThreadDetail } from './forum-contract'
import { MODULES } from '../catalog/modules'
import { MemberPrompt } from './MemberPrompt'
import type { Configuration } from '../config/workspace'
import { Icon } from '../components/Icon'
import { ForumPostBody as PostContent } from './ForumPostBody'
function date(value:string){return new Date(value.includes('T')?value:value.replace(' ','T')+'Z')}
function ForumTime({value,relative=false}:{value:string;relative?:boolean}){
  const [now,setNow]=useState(()=>Date.now())
  useEffect(()=>{if(!relative)return;const timer=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(timer)},[relative])
  const time=date(value),full=time.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}),minutes=Math.floor((now-time.getTime())/60000)
  const label=!relative?full:minutes<0?full:minutes<1?'Just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:minutes<10080?`${Math.floor(minutes/1440)}d ago`:time.toLocaleDateString(undefined,{month:'short',day:'numeric',...(time.getFullYear()!==new Date(now).getFullYear()?{year:'numeric' as const}:{})})
  return <time dateTime={time.toISOString()} title={full}>{label}</time>
}
function CategoryBadge({category}:{category:ForumCategory}){return <span className="forum-category-badge" data-category={category}><span aria-hidden="true"/>{FORUM_CATEGORIES[category]}</span>}
function Avatar({username}:{username:string|null}){return <span className="forum-avatar" aria-hidden="true">{username?.slice(0,2).toUpperCase()??'—'}</span>}
function errorText(error:unknown){return error instanceof Error?error.message:'The request could not be completed.'}
function ThreadRows({threads}:{threads:ForumThread[]}){return <div className="forum-thread-list"><div className="forum-list-columns" aria-hidden="true"><span>Discussion</span><span>Replies</span><span>Last active</span></div>{threads.map(thread=><article className="forum-thread-row" key={thread.id}><div className="forum-thread-summary"><div className="forum-thread-tags"><CategoryBadge category={thread.category}/>{!!thread.pinned&&<span className="forum-state"><Icon name="pin" size={13}/>Pinned</span>}{!!thread.locked&&<span className="forum-state"><Icon name="lock" size={13}/>Locked</span>}{thread.category==='issues'&&<span className="forum-state" data-resolved={thread.status==='resolved'}>{thread.status==='resolved'&&<Icon name="check" size={13}/>} {thread.status==='resolved'?'Resolved':'Open'}</span>}</div><h2><a href={'#forum/thread/'+thread.id}>{thread.title}</a></h2><div className="forum-meta"><a className="forum-author" href={'#forum/profile/'+thread.username}><Avatar username={thread.username}/>@{thread.username}</a>{thread.module_id&&<a className="forum-module-link" href={'#module/'+thread.module_id}>{MODULES.find(module=>module.id===thread.module_id)?.name??thread.module_id}</a>}</div></div><span className="forum-reply-count"><Icon name="message" size={15}/><span>{thread.replies}</span><small className="sr-only">{thread.replies===1?'reply':'replies'}</small></span><span className="forum-last-active"><ForumTime value={thread.updated_at} relative/></span></article>)}</div>}
function ForumList({query,profile}:{query:URLSearchParams;profile?:string}){
  const {session}=useCommunity(),[data,setData]=useState<{threads:ForumThread[];hasMore:boolean}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0)
  const serialized=query.toString(),category=query.get('category')??'',page=Number(query.get('page')??0)
  useEffect(()=>{let cancelled=false;void api<{threads:ForumThread[];hasMore:boolean}>('/forum/threads?'+serialized+(profile?'&author='+encodeURIComponent(profile):'')).then(value=>{if(!cancelled)setData(value)}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[serialized,profile,revision])
  function link(values:Record<string,string>){const next=new URLSearchParams(query);next.delete('page');for(const [key,value] of Object.entries(values)){if(value)next.set(key,value);else next.delete(key)}return (profile?'#forum/profile/'+encodeURIComponent(profile):'#forum')+(next.size?'?'+next.toString():'')}
  const saved=query.get('saved')==='1',filtered=!!query.get('q')||!!query.get('module')
  const heading=profile?'Public discussions':saved?'Your bookmarks':category&&Object.hasOwn(FORUM_CATEGORIES,category)?FORUM_CATEGORIES[category as ForumCategory]:'Latest discussions'
  const newParams=new URLSearchParams();if(category)newParams.set('category',category);if(query.get('module'))newParams.set('module',query.get('module')!)
  const startHref=session.user?.verified?'#forum/new'+(newParams.size?'?'+newParams.toString():''):session.user?'#account':'#account/register'
  return <>{profile&&<a className="back-link" href="#forum"><Icon name="back" size={14}/>All discussions</a>}<div className="page-heading forum-heading"><div><h1>{profile?'@'+profile:'Community forum'}</h1><p>{profile?'Public threads by this member.':'Talk mods, trade ideas, and share your next setup.'}</p></div><a className="button button-primary" href={startHref}><Icon name="plus" size={16}/>Start a thread</a></div>
    {!profile&&<><nav className="forum-categories" aria-label="Forum categories"><a aria-current={!category&&!saved?'page':undefined} href={link({category:'',saved:''})}>Latest</a>{Object.entries(FORUM_CATEGORIES).map(([key,label])=><a key={key} aria-current={category===key?'page':undefined} href={link({category:key,saved:''})}>{label}</a>)}{session.user?.verified&&<a aria-current={saved?'page':undefined} href={link({saved:'1',category:''})}><Icon name="bookmark" size={14}/>Bookmarks</a>}</nav><form role="search" className="forum-filters" onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);window.location.assign(link({q:String(values.get('q')??'').trim(),module:String(values.get('module')??'')}))}}><label className="forum-search"><span className="sr-only">Search discussions</span><Icon name="search" size={17}/><input name="q" type="search" defaultValue={query.get('q')??''} maxLength={120} placeholder="Search discussions…"/></label><label><span className="sr-only">Filter by module</span><select name="module" defaultValue={query.get('module')??''}><option value="">All modules</option>{MODULES.map(module=><option key={module.id} value={module.id}>{module.name}</option>)}</select></label><button className="button button-quiet">Search</button></form></>}
    <div className="forum-list-heading"><h2>{heading}</h2>{data&&!error&&<span>{data.threads.length}{data.hasMore?'+':''} {data.threads.length===1?'discussion':'discussions'}{page>0?' on this page':''}</span>}{filtered&&<a className="text-button" href={link({q:'',module:''})}><Icon name="close" size={13}/>Clear filters</a>}</div>
    {error?<div className="forum-empty" role="alert"><Icon name="message" size={26}/><h2>Discussions could not load</h2><p>{error}</p><button className="button button-quiet" onClick={()=>{setError('');setRevision(value=>value+1)}}>Try again</button></div>:!data?<div className="forum-loading" role="status"><span>Loading discussions…</span>{[0,1,2].map(row=><div className="forum-loading-row" key={row} aria-hidden="true"><span/><span/></div>)}</div>:data.threads.length?<ThreadRows threads={data.threads}/>:<div className="forum-empty"><Icon name={saved?'bookmark':'message'} size={28}/><h2>{filtered?'No matching discussions':profile?'No public threads yet':saved?'No bookmarks yet':'Be the first to start a conversation'}</h2><p>{filtered?'Try another search or clear your filters.':saved?'Bookmark a thread to keep it close for later.':profile?'Threads this member starts will appear here.':'Ask a question, share a discovery, or post a configuration you enjoy.'}</p><a className="button button-quiet" href={filtered?link({q:'',module:''}):saved||profile?'#forum':startHref}>{filtered?'Clear filters':saved||profile?'Browse discussions':'Start a thread'}</a></div>}
    {(page>0||data?.hasMore)&&<nav className="forum-pagination" aria-label="Discussion pages">{page>0?<a className="button button-quiet" href={link({page:String(page-1)})}><Icon name="back" size={14}/>Previous</a>:<span/>}<span>Page {page+1}</span>{data?.hasMore&&<a className="button button-quiet" href={link({page:String(page+1)})}>Next<Icon name="arrow" size={14}/></a>}</nav>}<MemberPrompt/>
  </>
}
function NewThread({configuration,query}:{configuration?:Configuration;query:URLSearchParams}){
  const {session}=useCommunity(),[category,setCategory]=useState<ForumCategory>((Object.hasOwn(FORUM_CATEGORIES,query.get('category')??'')?query.get('category'):'general') as ForumCategory),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(form:HTMLFormElement){setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(form)),payload:Record<string,unknown>={title:values.title,body:values.body,category,moduleId:values.moduleId};if(category==='configs'){if(!configuration)throw new Error('Create a local configuration first.');payload.configuration={name:configuration.name,moduleIds:configuration.moduleIds,moduleVersions:configuration.moduleVersions,keepStockFx2:configuration.keepStockFx2}}if(category==='issues')payload.issue={device:values.device,version:values.version,steps:values.steps,expected:values.expected,actual:values.actual};const result=await post<{id:string}>('/forum/threads',payload);window.location.assign('#forum/thread/'+result.id)}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  return <><a className="back-link" href="#forum"><Icon name="back" size={14}/>All discussions</a><div className="page-heading"><div><h1>Start a conversation</h1><p>A question, a discovery, or a configuration worth sharing.</p></div></div><MemberPrompt/>{session.user?.verified&&<div className="forum-compose-layout"><form className="community-form forum-composer" onSubmit={event=>{event.preventDefault();void submit(event.currentTarget)}}><div className="forum-composer-heading"><Avatar username={session.user.username}/><div><h2>Your discussion</h2><p>Posting as @{session.user.username}</p></div></div><div className="form-two-columns"><label>Category<select value={category} onChange={event=>setCategory(event.target.value as ForumCategory)}>{Object.entries(FORUM_CATEGORIES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>{category==='issues'?'Affected module':'Related module (optional)'}<select name="moduleId" required={category==='issues'} defaultValue={query.get('module')??''}><option value="">Choose a module</option>{MODULES.map(module=><option key={module.id} value={module.id}>{module.name}</option>)}</select></label></div><label>Title<input name="title" aria-label="Title" aria-describedby="forum-title-hint" required maxLength={160} placeholder="Give your discussion a clear title"/><span id="forum-title-hint" className="forum-field-hint">A specific title helps the right people find your thread.</span></label>
    {category==='configs'&&<aside className="forum-config"><h2>{configuration?.name??'No configuration selected'}</h2><p>{configuration?.moduleIds.map(id=>(MODULES.find(module=>module.id===id)?.name??id)+' '+configuration.moduleVersions[id]).join(' · ')||'Add modules to a local configuration first.'}</p><p>This publishes a fixed copy of the selected configuration. Firmware stays on your device.</p><a href="#configuration">Review your configuration →</a></aside>}
    {category==='issues'&&<fieldset><legend>Reproduction details</legend><label>Octatrack model<select name="device" required><option value="">Choose a model</option><option>MKI</option><option>MKII</option><option>Both</option></select></label><label>Module version<input name="version" required maxLength={80}/></label><label>Steps to reproduce<textarea name="steps" required maxLength={4000} rows={4}/></label><label>Expected result<textarea name="expected" required maxLength={2000} rows={2}/></label><label>Actual result<textarea name="actual" required maxLength={2000} rows={2}/></label><p className="service-note">This thread is public. For sensitive details, use the private issue form on the module page.</p></fieldset>}
    <label>{category==='issues'?'Summary and context':'Your post'}<textarea name="body" aria-label={category==='issues'?'Summary and context':'Your post'} aria-describedby="forum-post-hint" required maxLength={12000} rows={8} placeholder="Share enough detail for others to join in…"/><span id="forum-post-hint" className="forum-field-hint">Use &gt; for quotes and <code>```</code> around code or settings.</span></label><p className="service-note">Posts are public. Share only original or properly licensed content. Do not post firmware, dumps, passwords or personal information. File uploads are not supported.</p><button className="button button-primary" disabled={busy||(category==='configs'&&!configuration?.moduleIds.length)}>{busy?'Publishing…':'Publish thread'}<Icon name="arrow" size={15}/></button></form><aside className="forum-compose-tips"><h2>A good conversation starts here</h2><p><strong>Give it context.</strong><br/>Share the module, what you tried, and what you want to explore.</p><p><strong>Make it useful.</strong><br/>Include exact steps for a bug, or share a configuration others can try.</p><p><strong>Keep it kind.</strong><br/>Credit the people behind your ideas and leave room for different approaches.</p><p>For sensitive issues, use the private report form on the <a href="#library">module page</a>.</p></aside></div>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
function PostCard({item,author,locked,refresh,onQuote}:{item:ForumPost;author:string;locked:boolean;refresh:()=>Promise<void>;onQuote:(value:string)=>void}){
  const {session}=useCommunity(),[editing,setEditing]=useState(false),[body,setBody]=useState(item.body),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reporting,setReporting]=useState(false)
  async function act(path:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post(path,payload,method);setEditing(false);await refresh();return true}catch(error){setError(errorText(error));return false}finally{setBusy(false)}}
  return <article className="forum-post" id={'post-'+item.id}><header><Avatar username={item.username}/><div className="forum-post-author"><div>{item.username?<a href={'#forum/profile/'+item.username}>@{item.username}</a>:<strong>Removed post</strong>}{item.username===author&&<span className="forum-author-badge">Thread author</span>}{!!item.hidden&&<span className="pill">Hidden</span>}</div><div className="forum-meta"><ForumTime value={item.created_at}/>{item.edited_at&&<small>Edited</small>}</div></div></header>{item.hidden&&!session.admin?<p className="service-note">This post was removed.</p>:editing?<form className="community-form" onSubmit={event=>{event.preventDefault();void act('/forum/posts/'+item.id,{body},'PATCH')}}><label>Edit your post<textarea value={body} onChange={event=>setBody(event.target.value)} required maxLength={12000} rows={6}/></label><div className="forum-actions"><button className="button button-primary" disabled={busy}>Save changes</button><button type="button" className="button button-quiet" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form>:<PostContent body={item.body}/>}
    {!item.hidden&&<footer className="forum-post-actions">{session.user?.verified?<><button className="forum-post-action" disabled={busy} aria-label={`${item.liked?'Unlike':'Like'} this post (${item.likes} ${item.likes===1?'like':'likes'})`} aria-pressed={item.liked} onClick={()=>void act('/forum/posts/'+item.id+'/react',{liked:!item.liked})}><Icon name="heart" size={15}/> <span>{item.likes||'Like'}</span></button>{!locked&&<button className="forum-post-action" onClick={()=>onQuote('> @'+item.username+' wrote:\n'+item.body.split('\n').map(line=>'> '+line).join('\n')+'\n\n')}><Icon name="quote" size={15}/>Quote</button>}{item.canEdit&&<button className="forum-post-action" onClick={()=>{setBody(item.body);setEditing(true)}}>Edit</button>}<details open={reporting} onToggle={event=>setReporting(event.currentTarget.open)}><summary>Report</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const reason=new FormData(event.currentTarget).get('reason');void act('/forum/posts/'+item.id+'/report',{reason}).then(ok=>{if(ok){setNotice('Report submitted to the administrator.');setReporting(false)}})}}><p className="service-note">Reports go privately to the administrator.</p><label>Reason<textarea name="reason" required maxLength={1000} rows={2} placeholder="What should the administrator review?"/></label><div className="forum-actions"><button className="button button-quiet" disabled={busy}>Send report</button><button className="text-button" type="button" disabled={busy} onClick={()=>setReporting(false)}>Cancel</button></div></form></details></>:<span className="forum-readonly-likes"><Icon name="heart" size={15}/>{item.likes} {item.likes===1?'like':'likes'}</span>}</footer>}
    {session.admin&&<details><summary>Moderate post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));void act('/admin/forum/'+(fields.action==='suspended'?'users/'+item.user_id:'posts/'+item.id),{action:fields.action,value:fields.action==='hidden'?!item.hidden:true,reason:fields.reason},'PATCH')}}><label>Action<select name="action"><option value="hidden">{item.hidden?'Restore post':'Hide post'}</option><option value="suspended">Suspend author</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet" disabled={busy}>Apply</button></form></details>}{notice&&<p role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</article>
}
function ThreadPage({id,query,onCopy}:{id:string;query:URLSearchParams;onCopy:(config:SharedConfiguration)=>void}){
  const {session}=useCommunity(),[data,setData]=useState<ThreadDetail|null>(null),[error,setError]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const page=Number(query.get('page')??0)
  async function load(){setData(await api<ThreadDetail>('/forum/threads/'+id+'?page='+page))}
  useEffect(()=>{let cancelled=false;void api<ThreadDetail>('/forum/threads/'+id+'?page='+page).then(value=>{if(!cancelled)setData(value)}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[id,page])
  async function act(action:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post('/forum/threads/'+id+'/'+action,payload,method);await load();if(action==='replies'){setReply('');setNotice('Reply posted.')}}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  if(!data)return <><a href="#forum">← Forum</a>{error?<p className="file-error" role="alert">{error}</p>:<p role="status">Loading thread…</p>}</>
  const {thread}=data
  return <><a className="back-link" href="#forum"><Icon name="back" size={14}/>All discussions</a><div className="page-heading forum-thread-heading"><div><div className="forum-thread-tags"><CategoryBadge category={thread.category}/>{thread.module_id&&<a className="forum-module-link" href={'#module/'+thread.module_id}>{MODULES.find(module=>module.id===thread.module_id)?.name??thread.module_id}</a>}{!!thread.locked&&<span className="forum-state"><Icon name="lock" size={13}/>Locked</span>}{thread.category==='issues'&&<span className="forum-state" data-resolved={thread.status==='resolved'}>{thread.status==='resolved'?'Resolved':'Open'}</span>}</div><h1>{thread.title}</h1><div className="forum-meta"><a href={'#forum/profile/'+thread.username}>@{thread.username}</a><span>Started <ForumTime value={thread.created_at} relative/></span><span>{thread.replies} {thread.replies===1?'reply':'replies'}</span></div></div></div>
    {session.user?.verified&&<div className="forum-actions forum-thread-actions">{!thread.locked&&<button className="button button-primary" onClick={()=>document.getElementById('forum-reply')?.focus()}><Icon name="message" size={16}/>Reply</button>}<button className="button button-quiet" disabled={busy} aria-pressed={data.following} onClick={()=>void act('follow',{enabled:!data.following})}><Icon name={data.following?'check':'message'} size={15}/>{data.following?'Following':'Follow replies'}</button><button className="button button-quiet" disabled={busy} aria-pressed={data.bookmarked} onClick={()=>void act('bookmark',{enabled:!data.bookmarked})}><Icon name="bookmark" size={15}/>{data.bookmarked?'Bookmarked':'Bookmark'}</button>{thread.category==='issues'&&(thread.username===session.user.username||session.admin)&&<button className="button button-quiet" disabled={busy} onClick={()=>void act('status',{status:thread.status==='open'?'resolved':'open'},'PATCH')}><Icon name="check" size={15}/>{thread.status==='open'?'Mark resolved':'Reopen'}</button>}</div>}
    {data.configuration&&<aside className="forum-config"><h2>{data.configuration.name}</h2><ul>{data.configuration.moduleIds.map(module=><li key={module}>{MODULES.find(item=>item.id===module)?.name??module} <span className="subtle">{data.configuration!.moduleVersions[module]}</span></li>)}</ul><p>Stock FX2 {data.configuration.keepStockFx2?'preserved':'compact'}. Copy this snapshot to review compatibility and module availability before building.</p><button className="button button-primary" onClick={()=>{try{onCopy(data.configuration!)}catch(error){setError(errorText(error))}}}>Copy to my configurations</button></aside>}
    {data.issue&&<section className="forum-config"><h2>Reproduction details</h2><p>{data.issue.device} · {thread.module_id} · {data.issue.version}</p>{(['steps','expected','actual'] as const).map(key=><div key={key}><h3>{key==='steps'?'Steps to reproduce':key==='expected'?'Expected result':'Actual result'}</h3><PostContent body={data.issue![key]}/></div>)}</section>}
    {session.admin&&<details className="forum-config"><summary>Moderate thread</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));setError('');void post('/admin/forum/threads/'+id,{action:fields.action,value:fields.value==='true',reason:fields.reason},'PATCH').then(load).catch(error=>setError(errorText(error)))}}><label>Action<select name="action"><option value="locked">Lock</option><option value="pinned">Pin</option><option value="hidden">Hide</option></select></label><label>Set to<select name="value"><option value="true">On</option><option value="false">Off</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet">Apply</button></form></details>}
    {data.posts.map(item=><PostCard key={item.id} item={item} author={thread.username} locked={!!thread.locked} refresh={load} onQuote={value=>{setReply(current=>current+value);document.getElementById('forum-reply')?.focus()}}/>)}{(page>0||data.hasMore)&&<nav className="forum-pagination" aria-label="Reply pages">{page>0?<a className="button button-quiet" href={'#forum/thread/'+id+'?page='+(page-1)}><Icon name="back" size={14}/>Previous replies</a>:<span/>}<span>Page {page+1}</span>{data.hasMore&&<a className="button button-quiet" href={'#forum/thread/'+id+'?page='+(page+1)}>More replies<Icon name="arrow" size={14}/></a>}</nav>}
    <MemberPrompt/>{thread.locked?<p className="forum-locked-note"><Icon name="lock" size={16}/>This thread is locked. You can still read and bookmark it.</p>:session.user?.verified&&<form className="community-form forum-composer forum-reply-composer" onSubmit={event=>{event.preventDefault();void act('replies',{body:reply})}}><div className="forum-composer-heading"><Avatar username={session.user.username}/><div><label htmlFor="forum-reply">Join the discussion</label><p>Replying as @{session.user.username}</p></div></div><textarea id="forum-reply" value={reply} onChange={event=>setReply(event.target.value)} aria-describedby="forum-reply-hint" required maxLength={12000} rows={5} placeholder="Add your experience, an idea, or a question…"/><div className="forum-composer-footer"><span id="forum-reply-hint">Use &gt; for quotes and <code>```</code> for code.</span><button className="button button-primary" disabled={busy||!reply.trim()}>{busy?'Posting…':'Post reply'}<Icon name="arrow" size={15}/></button></div></form>}{notice&&<p className="success-note" role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
export function ForumPage({route,configuration,onCopy}:{route:string;configuration?:Configuration;onCopy:(config:SharedConfiguration)=>void}){
  const [path,search='']=route.split('?'),query=new URLSearchParams(search),segments=path.split('/')
  return <div className={'community-page forum-page'+(segments[1]==='thread'?' forum-reading-page':'')}>{segments[1]==='new'?<NewThread configuration={configuration} query={query}/>:segments[1]==='thread'&&segments[2]?<ThreadPage key={segments[2]+'?'+search} id={segments[2]} query={query} onCopy={onCopy}/>:<ForumList key={search+segments[2]} query={query} profile={segments[1]==='profile'?segments[2]:undefined}/>}</div>
}
