import { useEffect, useState } from 'react'
import { api, post } from './api'
type Report={id:string;reason:string;resolved:number;created_at:string;post_id:string;body:string;hidden:number;thread_id:string;user_id:string;username:string;title:string}
export function ForumModeration(){
 const [reports,setReports]=useState<Report[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{void api<Report[]>('/admin/forum/reports').then(setReports).catch(error=>setError(error.message))},[])
 async function act(item:Report,action:string,reason:string){setBusy(true);setError('');try{const group=action==='resolved'?'reports':action==='suspended'?'users':'posts',id=action==='resolved'?item.id:action==='suspended'?item.user_id:item.post_id;await post('/admin/forum/'+group+'/'+id,{action,value:action==='hidden'?!item.hidden:true,reason},'PATCH');setReports(await api<Report[]>('/admin/forum/reports'))}catch(error){setError(error instanceof Error?error.message:'Moderation failed.')}finally{setBusy(false)}}
 return <section className="configuration-section"><h2>Forum reports</h2>{reports===null&&!error?<p role="status">Loading reports…</p>:reports?.length?reports.map(item=><article className="forum-post" key={item.id}><header><a href={'#forum/thread/'+item.thread_id}>{item.title}</a><span className="pill">{item.resolved?'Reviewed':'Needs review'}</span></header><p>Reported: {item.reason}</p><p className="preserve-lines">@{item.username}: {item.body}</p><form className="community-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(item,String(form.get('action')),String(form.get('reason')))}}><label>Action<select name="action"><option value="resolved">Mark report reviewed</option><option value="hidden">{item.hidden?'Restore post':'Hide post'}</option><option value="suspended">Suspend author</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet" disabled={busy}>Apply</button></form></article>):<p className="service-note">No posts have been reported.</p>}{error&&<p className="file-error" role="alert">{error}</p>}</section>
}
