import { BackLink } from './BackLink'
import { moduleHref } from '../routing'
import recipes from '../catalog/module-sets.json'
import { MODULES, CATALOG_SOURCE } from '../catalog/modules'
import { isModuleAvailable } from '../catalog/availability'
import { ModulePreview } from './ModulePreview'
import { ModuleCommunity } from '../community/ModuleCommunity'
import { IssueReport } from '../community/IssueReport'
import { ModuleSetList } from './ModuleSetList'
function authorName(login:string){return MODULES.find(module=>module.author===login)?.authorName??login}
type Props={query:string;id?:string;onUse:(name:string,ids:string[])=>void;yours:Parameters<typeof ModuleSetList>[0]}
/** One page for module sets: your own on top, and the curated starting points below to copy. */
export function ModuleSets({id,onUse,query,yours}:Props){
 const availableRecipes=recipes.filter(recipe=>recipe.moduleIds.every(id => isModuleAvailable(id)))
 const visible=availableRecipes.filter(recipe=>(recipe.id+' '+recipe.description+' '+authorName(recipe.author)+' '+recipe.author).toLowerCase().includes(query.trim().toLowerCase()))
 const recipe=availableRecipes.find(item=>item.id===id)
 if(id&&!recipe)return <div className="no-results"><BackLink href="#module-sets">Module sets</BackLink><h1>Module set not found</h1><a className="button button-quiet" href="#module-sets">Browse module sets</a></div>
 if(recipe){const module=MODULES.find(m=>m.id===recipe.moduleIds[0])!;return <div className="detail-page module-set-detail"><BackLink href="#module-sets">Module sets</BackLink><section className="detail-hero"><ModulePreview id={module.id}/><div className="detail-intro"><span className="pill">Starting point</span><h1>{module.name} solo</h1><p>{recipe.description}</p><a className="author-link" href={'https://github.com/'+recipe.author} target="_blank" rel="noreferrer">by {authorName(recipe.author)} ↗</a><button className="button button-primary" onClick={()=>onUse(module.name+' solo',recipe.moduleIds)}>Use these modules</button></div></section><section className="detail-section"><h2>Source recipe & evidence</h2><p>{recipe.proofNote}</p><p className="service-note">This is the source recipe's historical record. Your local selection uses the current experimental catalog; it has not been qualified on hardware. Your configuration keeps the stock effects by default; you can shorten the FX2 chooser in its settings.</p><a className="text-button" href={CATALOG_SOURCE.repository+'/blob/'+CATALOG_SOURCE.revision+'/'+recipe.path} target="_blank" rel="noreferrer">Open module configuration source ↗</a></section><section className="detail-section"><h2>Included modules</h2>{recipe.moduleIds.map(id=>{const item=MODULES.find(m=>m.id===id)!;return <a className="module-set-module-row" key={id} href={moduleHref(id)}><ModulePreview id={id} compact/><span><strong>{item.name}</strong><small>{item.description}</small></span><span>→</span></a>})}</section><IssueReport id={'remix-'+recipe.id} author={recipe.author}/><ModuleCommunity id={'remix-'+recipe.id} mode="ratings"/></div>}
 return <div className="library-page"><BackLink href="#library">Module library</BackLink><div className="page-heading"><div><h1>Module sets</h1><p>Your own sets, and small starting points to copy.</p></div></div><ModuleSetList {...yours}/><div className="section-title"><h2>Starting points <span className="subtle">{visible.length}</span></h2></div><p className="service-note">Small recipes for getting to know one module, from the pinned source with their recorded evidence. Use one, then add modules in the library.</p><div className="module-set-list">{visible.map(recipe=>{const module=MODULES.find(m=>m.id===recipe.moduleIds[0])!;return <article className="module-set-row" key={recipe.id}><a href={'#module-set/'+recipe.id} className="module-set-art" aria-label={'View '+module.name+' solo'}><ModulePreview id={module.id}/></a><div><span className="guide-eyebrow">Starting point · {recipe.moduleIds.length} module</span><h2><a href={'#module-set/'+recipe.id}>{module.name} solo</a></h2><p>{recipe.description}</p><small>{recipe.proof==='hardware'?'Historical hardware evidence':'Render evidence'} · <a href={'https://github.com/'+recipe.author} target="_blank" rel="noreferrer">{authorName(recipe.author)}</a></small></div><a className="text-button" href={'#module-set/'+recipe.id}>Explore →</a></article>})}</div>{!visible.length&&<div className="no-results"><h2>No module sets found</h2><p>Try another module name, sound or author.</p></div>}</div>
}
